<a href="https://colab.research.google.com/github/dipinpjoseph/TheDataBundle/blob/master/ScrapBook/numpy_exp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
a1 = np.array([1,2,3])

In [0]:
a2 = np.array([[4,5,6],[5,6,7]])

In [0]:
np.add(a1,a2)

array([[ 5,  7,  9],
       [ 6,  8, 10]])

**Dot Product **

In [0]:
np.multiply(a1,a2)

array([[ 4, 10, 18],
       [ 5, 12, 21]])

In [0]:
a1 * a2

array([[ 4, 10, 18],
       [ 5, 12, 21]])

**Matrix Multiplication**

In [0]:
a2 @ a2.transpose()

array([[ 77,  92],
       [ 92, 110]])

In [0]:
np.zeros(9).reshape(3,3)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [0]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

**Solve eq - 3x+y=1 and 5x=2**



In [0]:
np.linalg.solve(np.array([[-3,1],[5,0]]),np.array([1,2]))

array([0.4, 2.2])

In [0]:
np.linalg.det(np.eye(3,3))

1.0

**Shallow Copy - View**

In [0]:
a = np.arange(6).reshape(3,2) 

In [31]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [0]:
b=a.view()

In [33]:
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [34]:
b.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [35]:
a  #No Change

array([[0, 1],
       [2, 3],
       [4, 5]])

In [0]:
b[1,1] = 10

In [37]:
b

array([[ 0,  1],
       [ 2, 10],
       [ 4,  5]])

In [38]:
a

array([[ 0,  1],
       [ 2, 10],
       [ 4,  5]])

In [40]:
id(a),id(b)

(140247602511664, 140247602510464)

**Deep Copy**





In [11]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [0]:
b = a.copy()

In [0]:
b[1,1] = 5

In [14]:
b

array([[0, 1],
       [2, 5],
       [4, 5]])

In [15]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [16]:
id(a),id(b)

(140247602769472, 140247602972592)

** No Copy **

In [41]:
a = np.arange(6).reshape(3,2) 
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [42]:
b=a
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [44]:
b[0,0] = 100
a,b

(array([[100,   1],
        [  2,   3],
        [  4,   5]]), array([[100,   1],
        [  2,   3],
        [  4,   5]]))

In [47]:
b.reshape(2,3)
a,b

(array([[100,   1],
        [  2,   3],
        [  4,   5]]), array([[100,   1],
        [  2,   3],
        [  4,   5]]))

In [46]:
id(a),id(b)

(140247602518896, 140247602518896)

**Universal Functions**

In [49]:
a = np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [50]:
np.exp(a)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
        5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
        8.10308393e+03]])

In [51]:
np.sqrt(a)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ]])

In [52]:
np.sin(a)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849]])

In [53]:
np.cos(a)

array([[ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362],
       [ 0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026]])