<a href="https://colab.research.google.com/github/dipinpjoseph/TheDataBundle/blob/master/ScrapBook/numpy_exp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
a1 = np.array([1,2,3])

In [0]:
a2 = np.array([[4,5,6],[5,6,7]])

In [5]:
np.add(a1,a2)

array([[ 5,  7,  9],
       [ 6,  8, 10]])

Dot Product 

In [6]:
np.multiply(a1,a2)

array([[ 4, 10, 18],
       [ 5, 12, 21]])

In [7]:
a1 * a2

array([[ 4, 10, 18],
       [ 5, 12, 21]])

Matrix Multiplication

In [10]:
a2 @ a2.transpose()

array([[ 77,  92],
       [ 92, 110]])

In [14]:
np.zeros(9).reshape(3,3)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

Solve eq - 3x+y=1 and 5x=2



In [20]:
np.linalg.solve(np.array([[-3,1],[5,0]]),np.array([1,2]))

array([0.4, 2.2])

In [24]:
np.linalg.det(np.eye(3,3))

1.0